# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a60dcc00c1d13a569660e2cca12b15d60809f66f7dad843ba6f643178e734f63c7067de64a6ec263863d8ce9b54ab020f20f5d9f9ea3e12c8dcbe606db1416f5

test:
  secret_key_base: 50c025d48d96ed2e35573fd846f240822b866b33e05ae5108d8719af40475f49adf572d22168637a51f1519d4d8f082811f07272412afd14e30502fc7d2fb1a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
